version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: Dockerfile
    image: facebooklikeapp
    platform: linux/x86_64
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py runserver 0.0.0.0:8000"
 

  redis:
    image: redis:6
    container_name: facebooklikeapp
    ports:
      - "6379:6379"