# Generated by Django 4.0.6 on 2022-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userfriendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='../files/profiles/default-cover-6.jpg', null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../files/profiles/default-profile-picture1.jpg', null=True, upload_to='profiles'),
        ),
    ]
