# Generated by Django 4.0.6 on 2022-08-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_bio_alter_profile_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
