# Generated by Django 4.0.6 on 2022-08-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group_about_group_admin_group_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_of_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment'),
        ),
    ]
